### ISSUE TITLE
./start_kie-server.sh: line 12: ip: command not found

### ISSUE THREAD

**Issue by alucardpj** [jboss-dockerfiles/drools#13]
In kie-server-showcase, the base image centos:7 does not contain "ip" command, so it cannot fetch the local ip address, the kie server location will be:

> Using 'http://:8080/kie-server/services/rest/server' as KIE server location

**Comment by psiroky** [comment]
@mbiarnes could you please take a look at this?

**Comment by ebirukov** [comment]
+1

**Comment by romartin** [comment]
Hello @alucardpj , you're right, the jboss base images has been moved to centos from fedora. Sorry for this issue, we didn't realized till now. 

@mbiarnes can you please fix this? Thanks!

**Comment by mbiarnes** [comment]
Looking at jboss-dockerfiles/base@328f451 we saw that the
image we inherit from, changed from fedora:20 to centos:7.
As the image of jboss-dockerfiles/base (https://github.com/jboss-dockerfiles/base) doesn't have tags the wildfly dockerfile (https://github.com/jboss-dockerfiles/wildfly/blob/master/Dockerfile) depends on each change of base dockerfile.
To determine the IP-address in Centos works is different then in Fedora.
There has been raised a PR #15 that should fix this.
When this has been merged you can pull the image again and run the container.
This was done locally and it worked.

**Comment by sashasch** [comment]
Hi,
- Port problem.
  I think, the problem here is not only host (DOCKER_IP), but also external port. Lets say, I'm using kie server image on the same machine with Workbench image on port 8180.

export KIE_SERVER_LOCATION="http://$DOCKER_IP:8080/$KIE_CONTEXT_PATH/services/rest/server"

will create the variable with wrong port in this case. 
- IP problem.
  The ip was determined after your last change 
  DOCKER_IP=$(hostname -I | cut -d" " -f 1)

but this is internal IP, which I don't want to expose, for example, via Workbench GUI.
May be, It can be  considered to pass the DOCKER_HOST and DOCKER_IP as environment variables via docker run command and use $(hostname -I | cut -d" " -f 1), 8080 as some default values?

**Comment by romartin** [comment]
Thanks @mbiarnes , I'm going to try it now and merge it if all good.  But before this would like to clarify @sashasch comments. 

First of all thanks for the feedback and help @sashasch. Those docker showcase images are considering that all containers are running in the same docker host, so all containers share network address and are visible between them using the internal ip address and so, the private public port as well. This is why we just take care of the internal docker IP addresses and the port is "hardcoded" to the internal exposed HTTP 8080  one, no matter the public addresses and ports, as all containers are running in same private LAN (the bridged network created by the daemon).

On the other hand, makes sense what you say, because as doing this the internal network map is displayed as for example on the Workbench GUI by the internal IP addresses. So I think it's fine just adding the possibility to specify DOCKER_HOST and DOCKER_IP via env variables when running the containers, if not founds, then using the internal network addresses and ports as it is doing now. Is it good for you?

**Comment by romartin** [comment]
Closing issue as it's merged and tested.

@sashasch Please try to pass the DOCKER_IP and DOCKER_PORT env vars from the command line and let's see if this works for you. Thanks!
